### ISSUE TITLE
Missing the resolvedValue implementation?

### ISSUE THREAD

**Issue by crazy4groovy** [jherr/jotai-rebuild#1]
I think you maybe missed adding this code?

![image](https://user-images.githubusercontent.com/1110812/223203579-2766b53f-b886-4905-8495-4ae28b96c734.png)

https://github.com/jherr/jotai-rebuild/blob/main/src/jotai.ts#L41

```
    if (newValue && typeof (newValue as any).then === "function") {
      value = null as AtomType;
      (newValue as any as Promise<AtomType>).then((resolvedValue) => {});
    } else {
      value = newValue;
    }
```

**Comment by jherr** [comment]
Huh, ok. Feel free to test and PR.
